# Survivor Data — Exploratory Data Analysis

Explore each table loaded in `src/load.py` to understand structure, nulls, and distributions.
Findings here drive the cleaning functions.

In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

xls = pd.ExcelFile("../data/survivoR.xlsx")

SHEETS = [
    "Castaways", "Castaway Details", "Episodes", "Vote History",
    "Challenge Results", "Confessionals", "Boot Mapping",
    "Advantage Details", "Advantage Movement", "Tribe Mapping",
]
data = {s: pd.read_excel(xls, sheet_name=s) for s in SHEETS}

def explore(name):
    """Print shape, column types, and null counts for a table."""
    df = data[name]
    print(f"Shape: {df.shape[0]:,} rows x {df.shape[1]} cols\n")
    nulls = df.isnull().sum()
    print("Columns:")
    for col in df.columns:
        n = nulls[col]
        pct = f"  — {n:,} nulls ({n/len(df)*100:.0f}%)" if n > 0 else ""
        print(f"  {col:30s} {str(df[col].dtype):12s}{pct}")
    print()
    return df.head(3)

## Overview — Table sizes

In [2]:
for name in SHEETS:
    df = data[name]
    print(f"{name:25s} {df.shape[0]:>6,} rows x {df.shape[1]:>2} cols")

Castaways                  1,417 rows x 26 cols
Castaway Details           1,180 rows x 22 cols
Episodes                   1,196 rows x 13 cols
Vote History               9,375 rows x 23 cols
Challenge Results         21,348 rows x 27 cols
Confessionals             13,559 rows x 10 cols
Boot Mapping              15,242 rows x 13 cols
Advantage Details            409 rows x  8 cols
Advantage Movement           934 rows x 15 cols
Tribe Mapping             14,975 rows x  9 cols

## Castaways

One row per castaway per season appearance (returnees appear multiple times).
Key table for player metadata per season: age, result, tribe, place.

In [3]:
explore("Castaways")

Shape: 1,417 rows x 26 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  full_name                      str
  castaway_id                    str
  castaway                       str
  age                            float64       — 24 nulls (2%)
  city                           str           — 36 nulls (3%)
  state                          str           — 87 nulls (6%)
  episode                        float64       — 24 nulls (2%)
  day                            float64       — 24 nulls (2%)
  order                          float64       — 24 nulls (2%)
  result                         str           — 24 nulls (2%)
  jury_status                    str           — 801 nulls (57%)
  place                          float64       — 24 nulls (2%)
  original_tribe                 str           — 26 nulls (2%)
  jury                           bool
  finalist                       float64       — 24 nulls (2%)
  winner                         float64       — 24 nulls (2%)
  acknowledge                    float64       — 690 nulls (49%)
  ack_look                       float64       — 690 nulls (49%)
  ack_speak                      float64       — 690 nulls (49%)
  ack_gesture                    float64       — 690 nulls (49%)
  ack_smile                      float64       — 690 nulls (49%)
  ack_quote                      str           — 1,099 nulls (78%)
  ack_score                      float64       — 690 nulls (49%)

,version,version_season,season,full_name,castaway_id,castaway,age,city,state,episode,day,order,result,jury_status,place,original_tribe,jury,finalist,winner,acknowledge,ack_look,ack_speak,ack_gesture,ack_smile,ack_quote,ack_score
0,US,US50,50,Angelina Keeley,US0554,Angelina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US,US50,50,Aubry Bracco,US0477,Aubry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US,US50,50,Charlie Davis,US0682,Charlie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = data["Castaways"]
print("version (franchise) distribution:")
print(df["version"].value_counts().to_string())
print(f"\nresult values:")
print(df["result"].value_counts().to_string())
print(f"\njury_status values:")
print(df["jury_status"].value_counts(dropna=False).head(10).to_string())

version (franchise) distribution:
version
US    917
AU    254
SA    166
UK     46
NZ     34

result values:
result
Runner-up                      82
10th voted out                 74
Sole Survivor                  74
2nd voted out                  72
5th voted out                  72
1st voted out                  71
3rd voted out                  71
6th voted out                  71
7th voted out                  71
9th voted out                  71
4th voted out                  70
11th voted out                 70
8th voted out                  69
12th voted out                 69
13th voted out                 67
14th voted out                 56
15th voted out                 36
2nd runner-up                  34
Medically evacuated            28
16th voted out                 26
Quit                           24
17th voted out                 17
Lost final 4 fire challenge    15
Eliminated                     14
18th voted out                 11
19th voted out                 10
20th voted out                  9
21st voted out                  9
Lost fire challenge             6
22nd voted out                  6
23rd voted out                  5
24th voted out                  2
3rd voted out; Quit             1
8th voted out; Quit EoE         1
Ejected                         1
2nd voted out; Quit EoE         1
6th voted out; Quit EoE         1
Withdrew                        1
Switched                        1
1st voted out (Quit)            1
17th voted out; Quit            1
Evacuated                       1
Tied destiny                    1

jury_status values:
jury_status
NaN                801
2nd jury member     74
4th jury member     74
5th jury member     74
1st jury member     73
3rd jury member     73
7th jury member     71
6th jury member     69
8th jury member     52
9th jury member     30

## Castaway Details

One row per unique castaway (across all appearances).
Demographics, personality type, occupation.

In [5]:
explore("Castaway Details")

Shape: 1,180 rows x 22 cols

Columns:
  castaway_id                    str
  full_name                      str           — 2 nulls (0%)
  full_name_detailed             str           — 2 nulls (0%)
  castaway                       str
  last_name                      str           — 2 nulls (0%)
  date_of_birth                  datetime64[us]  — 281 nulls (24%)
  date_of_death                  datetime64[us]  — 1,163 nulls (99%)
  gender                         str
  african                        float64       — 427 nulls (36%)
  asian                          float64       — 427 nulls (36%)
  latin_american                 float64       — 427 nulls (36%)
  native_american                float64       — 427 nulls (36%)
  bipoc                          float64       — 427 nulls (36%)
  lgbt                           float64       — 2 nulls (0%)
  personality_type               str           — 433 nulls (37%)
  occupation                     str           — 2 nulls (0%)
  collar                         str           — 42 nulls (4%)
  three_words                    str           — 720 nulls (61%)
  hobbies                        str           — 739 nulls (63%)
  pet_peeves                     str           — 771 nulls (65%)
  race                           str           — 1,005 nulls (85%)
  ethnicity                      str           — 1,066 nulls (90%)

,castaway_id,full_name,full_name_detailed,castaway,last_name,date_of_birth,date_of_death,gender,african,asian,latin_american,native_american,bipoc,lgbt,personality_type,occupation,collar,three_words,hobbies,pet_peeves,race,ethnicity
0,US0001,Sonja Christopher,Sonja Christopher,Sonja,Christopher,1937-01-28,2024-04-26,Female,0.0,0.0,0.0,0.0,0.0,1.0,ENFP,Musician,No collar,NaN,NaN,NaN,NaN,NaN
1,US0002,B.B. Andersen,B.B. Andersen,B.B.,Andersen,1936-01-18,2013-10-29,Male,0.0,0.0,0.0,0.0,0.0,0.0,ESTJ,Real Estate Developer,White collar,NaN,NaN,NaN,NaN,NaN
2,US0003,Stacey Stillman,Stacey Stillman,Stacey,Stillman,1972-08-11,NaT,Female,0.0,0.0,0.0,0.0,0.0,0.0,ENTJ,Attorney,White collar,NaN,NaN,NaN,NaN,NaN

In [6]:
df = data["Castaway Details"]
print("gender:")
print(df["gender"].value_counts().to_string())
print(f"\npersonality_type (top 5):")
print(df["personality_type"].value_counts().head().to_string())
print(f"\ncollar:")
print(df["collar"].value_counts(dropna=False).to_string())
print(f"\ndate_of_birth range: {df['date_of_birth'].min()} to {df['date_of_birth'].max()}")

gender:
gender
Male          589
Female        587
Non-binary      4

personality_type (top 5):
personality_type
ENFP    83
ESFP    72
ISFP    59
ESTP    55
INFP    55

collar:
collar
White collar    612
No collar       291
Blue collar     197
NaN              42
Unknown          38

date_of_birth range: 1928-01-20 00:00:00 to 2002-10-13 00:00:00

## Episodes

One row per episode across all versions/seasons.
Useful for episode dates (needed to compute player age at time of season).

In [7]:
explore("Episodes")

Shape: 1,196 rows x 13 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  episode_number_overall         float64       — 46 nulls (4%)
  episode                        int64
  episode_title                  str
  episode_label                  str
  episode_date                   datetime64[us]  — 14 nulls (1%)
  episode_length                 float64       — 101 nulls (8%)
  viewers                        float64       — 379 nulls (32%)
  imdb_rating                    float64       — 117 nulls (10%)
  n_ratings                      float64       — 117 nulls (10%)
  episode_summary                str           — 511 nulls (43%)

,version,version_season,season,episode_number_overall,episode,episode_title,episode_label,episode_date,episode_length,viewers,imdb_rating,n_ratings,episode_summary
0,US,US49,49,663.0,1,Act One of a Horror Film,Ep 1,2025-09-24,86.0,4030000.0,6.4,201.0,The 18 new castaways arrived in Fiji by boat t...
1,US,US49,49,664.0,2,Cinema,Ep 2,2025-10-01,65.0,4030000.0,6.6,151.0,"At Kele, Alex and Jake found a beware advantag..."
2,US,US49,49,665.0,3,Lovable Losers,Ep 3,2025-10-08,64.0,4230000.0,7.0,163.0,"At Kele, on the morning of the Immunity Challe..."

In [9]:
df = data["Episodes"]
print(f"episode_date range: {df['episode_date'].min()} to {df['episode_date'].max()}")
print(f"\nversion distribution:")
print(df["version"].value_counts().to_string())
print(f"\nepisode_label samples:")
print(df["episode_label"].value_counts().head(10).to_string())

episode_date range: 2000-05-31 00:00:00 to 2025-12-17 00:00:00

version distribution:
version
US    714
AU    256
SA    149
UK     42
NZ     35

episode_label samples:
episode_label
Ep 1      74
Ep 2      74
Ep 3      74
Ep 4      74
Ep 5      74
Finale    74
Ep 6      73
Ep 8      73
Ep 7      72
Ep 9      71

## Vote History

One row per castaway per vote event (casting a vote at tribal council).
Core table for building voting features.

In [9]:
explore("Vote History")

Shape: 9,375 rows x 23 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  episode                        int64
  day                            int64
  tribe_status                   str
  tribe                          str
  castaway                       str           — 8 nulls (0%)
  immunity                       str           — 8,303 nulls (89%)
  vote                           str           — 549 nulls (6%)
  vote_event                     str           — 8,747 nulls (93%)
  vote_event_outcome             str           — 8,747 nulls (93%)
  split_vote                     str           — 8,828 nulls (94%)
  nullified                      float64       — 2 nulls (0%)
  tie                            float64       — 105 nulls (1%)
  voted_out                      str
  order                          int64
  vote_order                     int64
  castaway_id                    str           — 8 nulls (0%)
  vote_id                        str           — 549 nulls (6%)
  voted_out_id                   str
  sog_id                         int64
  challenge_id                   float64       — 75 nulls (1%)

,version,version_season,season,episode,day,tribe_status,tribe,castaway,immunity,vote,vote_event,vote_event_outcome,split_vote,nullified,tie,voted_out,order,vote_order,castaway_id,vote_id,voted_out_id,sog_id,challenge_id
0,US,US49,49,1,2,Original,Kele,Alex,NaN,Nicole,NaN,NaN,NaN,0.0,0.0,Nicole,1,1,US0734,US0744,US0744,1,3.0
1,US,US49,49,1,2,Original,Kele,Annie,NaN,Nicole,NaN,NaN,NaN,0.0,0.0,Nicole,1,1,US0735,US0744,US0744,1,3.0
2,US,US49,49,1,2,Original,Kele,Jake,NaN,Nicole,NaN,NaN,NaN,0.0,0.0,Nicole,1,1,US0736,US0744,US0744,1,3.0

In [10]:
df = data["Vote History"]
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"\nimmunity values:")
print(df["immunity"].value_counts(dropna=False).head(10).to_string())
print(f"\nvote_order values:")
print(df["vote_order"].value_counts(dropna=False).to_string())
print(f"\ntribe_status values:")
print(df["tribe_status"].value_counts().to_string())

Duplicate rows: 2

immunity values:
immunity
NaN                        8303
Individual                  788
Hidden                      227
Removed from tribal          31
Earned merge                  6
Deadlock                      6
Salvation                     6
Shot in the dark (safe)       2
Do or Die                     2
Hidden (nullified)            2

vote_order values:
vote_order
1    8669
2     626
3      76
4       4

tribe_status values:
tribe_status
Merged       5018
Original     2771
Swapped      1074
Swapped_2     390
Swapped_3      70
Mergatory      45
Swapped_4       7

## Challenge Results

One row per castaway per challenge.
Needed for immunity wins, sit-outs, challenge performance features.

In [11]:
explore("Challenge Results")

Shape: 21,348 rows x 27 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  episode                        int64
  n_boots                        int64
  castaway_id                    str
  castaway                       str
  tribe                          str           — 185 nulls (1%)
  tribe_status                   str
  challenge_type                 str
  outcome_type                   str
  team                           str           — 20,291 nulls (95%)
  result                         str
  result_notes                   str           — 21,229 nulls (99%)
  chosen_for_reward              bool
  challenge_id                   int64
  sit_out                        float64       — 6,592 nulls (31%)
  order_of_finish                float64       — 7,152 nulls (34%)
  sog_id                         int64
  won                            float64       — 201 nulls (1%)
  won_tribal_reward              float64       — 201 nulls (1%)
  won_tribal_immunity            float64       — 201 nulls (1%)
  won_team_reward                float64       — 201 nulls (1%)
  won_team_immunity              float64       — 201 nulls (1%)
  won_individual_reward          float64       — 201 nulls (1%)
  won_individual_immunity        float64       — 201 nulls (1%)
  won_duel                       float64       — 201 nulls (1%)

,version,version_season,season,episode,n_boots,castaway_id,castaway,tribe,tribe_status,challenge_type,outcome_type,team,result,result_notes,chosen_for_reward,challenge_id,sit_out,order_of_finish,sog_id,won,won_tribal_reward,won_tribal_immunity,won_team_reward,won_team_immunity,won_individual_reward,won_individual_immunity,won_duel
0,US,US49,49,1,0,US0737,Jason,Hina,Original,Reward,Tribal,NaN,Won,NaN,False,1,0.0,1.0,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,US,US49,49,1,0,US0740,Kristina,Hina,Original,Reward,Tribal,NaN,Won,NaN,False,1,0.0,1.0,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,US,US49,49,1,0,US0741,Matt,Hina,Original,Reward,Tribal,NaN,Won,NaN,False,1,0.0,1.0,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df = data["Challenge Results"]
print("challenge_type:")
print(df["challenge_type"].value_counts().to_string())
print(f"\noutcome_type:")
print(df["outcome_type"].value_counts().to_string())
print(f"\nresult:")
print(df["result"].value_counts().to_string())
print(f"\ntribe_status:")
print(df["tribe_status"].value_counts().to_string())

challenge_type:
challenge_type
Immunity               10426
Reward                  7774
Immunity and Reward     2954
Duel                     184
Captains Duel             10

outcome_type:
outcome_type
Tribal                 13946
Individual              6058
Team                    1118
Team / Individual        162
Tribal / Individual       64

result:
result
Lost                   12546
Won                     8700
Won (reward only)         75
Draw                      15
Won (immunity only)       12

tribe_status:
tribe_status
Original              9124
Merged                6936
Swapped               3533
Swapped_2             1269
Swapped_3              211
Redemption Island      111
Mergatory               64
Edge of Extinction      39
Swapped_4               26
Not yet selected        18
Exile Beach             11
Dead Man's Island        4
Redemption Rock          2

## Confessionals

One row per castaway per episode.
Confessional count is well-populated; confessional *time* is mostly null (recent seasons only).

In [13]:
explore("Confessionals")

Shape: 13,559 rows x 10 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  episode                        int64
  castaway                       str
  castaway_id                    str
  confessional_count             int64
  confessional_time              float64       — 11,503 nulls (85%)
  exp_count                      float64       — 996 nulls (7%)
  exp_time                       float64       — 11,695 nulls (86%)

  version version_season  season  episode castaway castaway_id  confessional_count  confessional_time  exp_count    exp_time
0      US           US49      49        1     Alex      US0734                  11              200.0   8.265485  150.281537
1      US           US49      49        1    Annie      US0735                   2               49.0   4.435779  108.676581
2      US           US49      49        1     Jake      US0736                   8              133.0   4.435779   73.744823

In [14]:
df = data["Confessionals"]
print(f"confessional_count range: {df['confessional_count'].min()} – {df['confessional_count'].max()}")
print(f"confessional_time populated: {df['confessional_time'].notna().sum()} / {len(df)}")
print(f"\nversion distribution:")
print(df["version"].value_counts().to_string())

confessional_count range: 0 – 22
confessional_time populated: 2056 / 13559

version distribution:
version
US    7808
AU    3381
SA    1617
UK     397
NZ     356

## Boot Mapping

One row per castaway per episode (all players still in the game).
**Closest table to the target modeling structure** — tracks game_status per episode.

In [15]:
explore("Boot Mapping")

Shape: 15,242 rows x 13 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  episode                        int64
  order                          int64
  n_boots                        float64       — 1,116 nulls (7%)
  final_n                        float64       — 1,149 nulls (8%)
  sog_id                         int64
  castaway_id                    str
  castaway                       str
  tribe                          str           — 396 nulls (3%)
  tribe_status                   str           — 2 nulls (0%)
  game_status                    str

  version version_season  season  episode  order  n_boots  final_n  sog_id castaway_id  castaway tribe tribe_status  game_status
0      US           US50      50        1      0      0.0     24.0       1      US0554  Angelina   NaN     Original  In the game
1      US           US50      50        1      0      0.0     24.0       1      US0477     Aubry   NaN     Original  In the game
2      US           US50      50        1      0      0.0     24.0       1      US0682   Charlie   NaN     Original  In the game

In [8]:
df = data["Boot Mapping"]
df[df['version_season'] == "US49"].tail(20)

    version version_season  season  episode  order  n_boots  final_n  sog_id castaway_id  castaway   tribe tribe_status  game_status
175      US           US49      49       12     12     12.0      6.0      13      US0745      Rizo  Lewatu       Merged  In the game
176      US           US49      49       12     12     12.0      6.0      13      US0747  Savannah  Lewatu       Merged  In the game
177      US           US49      49       12     12     12.0      6.0      13      US0751    Steven  Lewatu       Merged  In the game
178      US           US49      49       12     12     12.0      6.0      13      US0746      Sage  Lewatu       Merged  In the game
179      US           US49      49       12     12     12.0      6.0      13      US0740  Kristina  Lewatu       Merged  In the game
180      US           US49      49       13     13     13.0      5.0      14      US0749     Sophi  Lewatu       Merged  In the game
181      US           US49      49       13     13     13.0      5.0      14      US0745      Rizo  Lewatu       Merged  In the game
182      US           US49      49       13     13     13.0      5.0      14      US0747  Savannah  Lewatu       Merged  In the game
183      US           US49      49       13     13     13.0      5.0      14      US0746      Sage  Lewatu       Merged  In the game
184      US           US49      49       13     13     13.0      5.0      14      US0740  Kristina  Lewatu       Merged  In the game
185      US           US49      49       13     14     14.0      4.0      15      US0749     Sophi  Lewatu       Merged  In the game
186      US           US49      49       13     14     14.0      4.0      15      US0745      Rizo  Lewatu       Merged  In the game
187      US           US49      49       13     14     14.0      4.0      15      US0747  Savannah  Lewatu       Merged  In the game
188      US           US49      49       13     14     14.0      4.0      15      US0746      Sage  Lewatu       Merged  In the game
189      US           US49      49       13     15     15.0      3.0      16      US0749     Sophi  Lewatu       Merged  In the game
190      US           US49      49       13     15     15.0      3.0      16      US0747  Savannah  Lewatu       Merged  In the game
191      US           US49      49       13     15     15.0      3.0      16      US0746      Sage  Lewatu       Merged  In the game
192      US           US49      49       13     16     16.0      2.0      17      US0749     Sophi  Lewatu       Merged  In the game
193      US           US49      49       13     16     16.0      2.0      17      US0747  Savannah  Lewatu       Merged  In the game
194      US           US49      49       13     17     17.0      1.0      18      US0747  Savannah  Lewatu       Merged  In the game

In [16]:
df = data["Boot Mapping"]
print("game_status values:")
print(df["game_status"].value_counts().to_string())
print(f"\ntribe_status values:")
print(df["tribe_status"].value_counts().to_string())

game_status values:
game_status
In the game           14856
Edge of Extinction      200
Redemption Island       143
Returned                 21
Dead Man's Island         8
Purgatory                 5
Redemption Rock           3
Never started             2
Survivor Isolation        2
Exile Beach               2

tribe_status values:
tribe_status
Original              6093
Merged                5209
Swapped               2462
Swapped_2              838
Edge of Extinction     200
Swapped_3              156
Redemption Island      145
Mergatory              100
Swapped_4               13
Dead Man's Island       10
Purgatory                5
Exile Beach              5
Redemption Rock          4

## Advantage Details

One row per advantage per season. Small reference table.

In [17]:
explore("Advantage Details")

Shape: 409 rows x 8 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  advantage_id                   int64
  advantage_type                 str
  clue_details                   str
  location_found                 str           — 8 nulls (2%)
  conditions                     str           — 211 nulls (52%)

  version version_season  season  advantage_id        advantage_type clue_details     location_found        conditions
0      US           US49      49             1  Hidden Immunity Idol      No clue  Found around camp  Beware advantage
1      US           US49      49             2   Challenge Advantage      No clue     Won on Journey               NaN
2      US           US49      49             3  Hidden Immunity Idol      No clue  Found around camp  Beware advantage

In [18]:
df = data["Advantage Details"]
print("advantage_type values:")
print(df["advantage_type"].value_counts().to_string())

advantage_type values:
advantage_type
Hidden Immunity Idol                         289
Extra Vote                                    19
Challenge Advantage                           14
Steal a Vote                                   9
Amulet                                         9
Hidden Immunity Idol Half                      8
Knowledge is Power                             7
Safety without Power                           5
Idol Nullifier                                 5
Vote Blocker                                   4
Super Idol                                     4
Bank your Vote                                 3
Block a Vote                                   3
Reward Stealer                                 2
Moral Dilemma                                  2
Remove Jury Member                             2
Diplomatic Immunity                            2
Practice Advantage                             2
Hidden Immunity Idol Clue                      2
Black Cowrie                                   2
Goodwill Advantage                             1
Inheritance Advantage                          1
Control the Vote                               1
Choose your Champion                           1
Advantage Menu                                 1
Preventative Hidden Immunity Idol              1
Ultimate Vote                                  1
Voter Remover                                  1
Vote Steal                                     1
Kidnap Castaway from Other Tribe               1
Tribal Council Pass                            1
Outsurance Reward Send Token                   1
Save the Date                                  1
Coin Flip                                      1
White Cowrie                                   1
Disadvantage Future Vote Cast Against you      1

## Advantage Movement

One row per advantage event (found, played, transferred, etc.).

In [19]:
explore("Advantage Movement")

Shape: 934 rows x 15 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  castaway                       str
  castaway_id                    str
  advantage_id                   int64
  sequence_id                    int64
  day                            float64       — 17 nulls (2%)
  episode                        float64       — 17 nulls (2%)
  event                          str
  played_for                     str           — 647 nulls (69%)
  played_for_id                  str           — 649 nulls (69%)
  success                        str           — 645 nulls (69%)
  votes_nullified                float64       — 721 nulls (77%)
  sog_id                         float64       — 26 nulls (3%)

,version,version_season,season,castaway,castaway_id,advantage_id,sequence_id,day,episode,event,played_for,played_for_id,success,votes_nullified,sog_id
0,US,US49,49,Alex,US0734,1,1,4.0,2.0,Found (beware),NaN,NaN,NaN,NaN,2.0
1,US,US49,49,Alex,US0734,1,2,4.0,2.0,Found,NaN,NaN,NaN,NaN,2.0
2,US,US49,49,Alex,US0734,1,3,7.0,3.0,Played,Alex,US0734,Not needed,1.0,4.0

In [20]:
df = data["Advantage Movement"]
print("event values:")
print(df["event"].value_counts().to_string())
print(f"\nsuccess values:")
print(df["success"].value_counts(dropna=False).to_string())

event values:
event
Found                                 395
Played                                300
Received                               86
Voted out with advantage               62
Expired                                30
Found (beware)                         26
Activated                               5
Became steal a vote                     4
Absorbed                                4
Recieved                                3
Stolen                                  3
Won                                     3
Banked                                  2
Left game with advantage                2
Became hidden immunity idol             2
Bought                                  2
Destroyed                               1
Medically evacuated with advantage      1
Quit with advantage                     1
Discarded                               1
Lost                                    1

success values:
success
NaN           645
Not needed    143
Yes           110
No             36

## Tribe Mapping

One row per castaway per episode — tracks which tribe each player is on.
Essential for tracking swaps and merges.

In [21]:
explore("Tribe Mapping")

Shape: 14,975 rows x 9 cols

Columns:
  version                        str
  version_season                 str
  season                         int64
  episode                        int64
  day                            float64       — 1,856 nulls (12%)
  castaway_id                    str
  castaway                       str
  tribe                          str           — 379 nulls (3%)
  tribe_status                   str

  version version_season  season  episode  day castaway_id  castaway tribe tribe_status
0      US           US50      50        1  NaN      US0554  Angelina   NaN     Original
1      US           US50      50        1  NaN      US0477     Aubry   NaN     Original
2      US           US50      50        1  NaN      US0682   Charlie   NaN     Original

In [12]:
df = data["Tribe Mapping"]
print("tribe_status values:")
print(df["tribe_status"].value_counts().to_string())
print(f"\nUnique tribes: {df['tribe'].nunique()}")

tribe_status values:
tribe_status
Original              6135
Merged                5044
Swapped               2401
Swapped_2              805
Edge of Extinction     190
Swapped_3              156
Redemption Island      155
Mergatory               51
Dead Man's Island       15
Swapped_4               13
Purgatory                4
Redemption Rock          3
Exile Beach              3

Unique tribes: 251